// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaF_UQIMKQKSC7yhBvxDEGaZKgL30JQho',
    appId: '1:978808974190:web:a7b572d3e52f2a26a72f7f',
    messagingSenderId: '978808974190',
    projectId: 'nti-todo-e6eee',
    authDomain: 'nti-todo-e6eee.firebaseapp.com',
    storageBucket: 'nti-todo-e6eee.firebasestorage.app',
    measurementId: 'G-DZNE8NT1YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYrvdj2BrDq5yqrfxN6wt-a3SwaYZGey4',
    appId: '1:978808974190:android:cd60fba7947570aaa72f7f',
    messagingSenderId: '978808974190',
    projectId: 'nti-todo-e6eee',
    storageBucket: 'nti-todo-e6eee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL1knn4YMDQs4DMvUu_s0c2LXcfGC8vRw',
    appId: '1:978808974190:ios:84f61695ea59a451a72f7f',
    messagingSenderId: '978808974190',
    projectId: 'nti-todo-e6eee',
    storageBucket: 'nti-todo-e6eee.firebasestorage.app',
    iosBundleId: 'com.example.ntiTodoApp',
  );
}
